### ISSUE TITLE
Tool is broken since 774d1fd28268 ("Add support for single flow dump feature")

### ISSUE THREAD

**Issue by david-marchand** [Mellanox/mlx_steering_dump#27]
Mix of tabs and space triggers following error:

Traceback (most recent call last):
  File "mlx_steering_dump_parser.py", line 37, in <module>
    from src import dr_trigger
  File "/root/mlx_steering_dump/src/dr_trigger.py", line 58
    if (flow_ptr > 0xFFFFFFFF):
                              ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by kliteyn** [comment]
Thanks, fixed:

    Commit da7b0b0c7b0624e502b9e2edd1992624bb4e53ef
    Author: Muhammad Sammar <muhammads@nvidia.com>
    Date:   Fri Mar 5 01:02:39 2021 +0200

    Fix mixed spaces and tabs error in dr_trigger.py
